# -*- coding: utf-8 -*-
"""train-test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jvOnmY7j1qEnbnNROppXb3ZKKG7u4Zup
"""

import numpy as np
import cv2
import os
import random
import matplotlib.pyplot as plt
import pickle

DIRECTORY=r'C:\Users\TR\OneDrive\Masaüstü\Global ai hub\transfer_learning_project\kagglecatsanddogs_5340\PetImages'
CATEGORIES=["Cat","Dog"]

data=[]

for category in CATEGORIES:
        folder=os.path.join(DIRECTORY,category)
        label=CATEGORIES.index(category)
        for img in os.listdir(folder):
            try:
                img_path =os.path.join(folder,img)
                img_arr =plt.imread(img_path)
                img_arr = cv2.resize(img_arr,(200,200))
                if(img_arr.shape==(200,200,3)):
                    data.append([img_arr,label])
                else:
                    print(img_path)
            except Exception as e:
                print(str(e))

len(data)

random.shuffle(data)

X_train=[]
y_train=[]
X_val=[]
y_val=[]
X_test=[]
y_test=[]
for f,l in data[:18000]:
    X_train.append(f)
    y_train.append(l)
for f,l in data[18000:20000]:
    X_val.append(f)
    y_val.append(l)
for f,l in data[20000:]:
    X_test.append(f)
    y_test.append(l)

X_train=np.array(X_train)
y_train=np.array(y_train)
X_val=np.array(X_val)
y_val=np.array(y_val)
X_test=np.array(X_test)
y_test=np.array(y_test)

X_train.shape

y_train.shape

X_test.shape

y_test.shape

y_test[0]

pickle.dump(X_train,open('X_train.pkl','wb'))
pickle.dump(y_train,open('y_train.pkl','wb'))
pickle.dump(X_train,open('X_val.pkl','wb'))
pickle.dump(y_train,open('y_val.pkl','wb'))
pickle.dump(X_test,open('X_test.pkl','wb'))
pickle.dump(y_test,open('y_test.pkl','wb'))

